feature comments
StRaiGT/java-explore-with-me pull request #3
Opened 2023-03-29 15:44 UTC by StRaiGT

2023-03-29 16:17 UTC, StRaiGT commented
гит опять не хочет запускать проверку (( проблема массовая

2023-03-30 08:25 UTC, AnastasiyaFomkina requested changes
Клево, что написал тесты 💪

2023-03-30 08:30 UTC, StRaiGT commented on main-service/src/main/java/ru/practicum/main_service/comment/mapper/CommentMapper.java
> +    Comment toComment(NewCommentDto newCommentDto, User author, Event event, LocalDateTime createdOn);
done

2023-03-30 12:30 UTC, AnastasiyaFomkina approved these changes

2023-03-30 12:49 UTC, merged